/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIdRouteImport } from './routes/venues.$id'
import { Route as StagesIdRouteImport } from './routes/stages.$id'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStaffVenuesRouteImport } from './routes/_authenticated/staff/venues'
import { Route as AuthenticatedStaffVendorsRouteImport } from './routes/_authenticated/staff/vendors'
import { Route as AuthenticatedStaffSponsorsRouteImport } from './routes/_authenticated/staff/sponsors'
import { Route as AuthenticatedStaffSettingsRouteImport } from './routes/_authenticated/staff/settings'
import { Route as AuthenticatedStaffRoomReservationsRouteImport } from './routes/_authenticated/staff/room-reservations'
import { Route as AuthenticatedStaffMapRouteImport } from './routes/_authenticated/staff/map'
import { Route as AuthenticatedStaffCommunityMusicRouteImport } from './routes/_authenticated/staff/community-music'
import { Route as AuthenticatedStaffCommunityEventsRouteImport } from './routes/_authenticated/staff/community-events'
import { Route as AuthenticatedStaffAttendeesRouteImport } from './routes/_authenticated/staff/attendees'
import { Route as AuthenticatedStaffAdminRouteImport } from './routes/_authenticated/staff/admin'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIdRoute = VenuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VenuesRoute,
} as any)
const StagesIdRoute = StagesIdRouteImport.update({
  id: '/stages/$id',
  path: '/stages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffVenuesRoute =
  AuthenticatedStaffVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffVendorsRoute =
  AuthenticatedStaffVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSponsorsRoute =
  AuthenticatedStaffSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSettingsRoute =
  AuthenticatedStaffSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffRoomReservationsRoute =
  AuthenticatedStaffRoomReservationsRouteImport.update({
    id: '/room-reservations',
    path: '/room-reservations',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffMapRoute = AuthenticatedStaffMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffCommunityMusicRoute =
  AuthenticatedStaffCommunityMusicRouteImport.update({
    id: '/community-music',
    path: '/community-music',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCommunityEventsRoute =
  AuthenticatedStaffCommunityEventsRouteImport.update({
    id: '/community-events',
    path: '/community-events',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAttendeesRoute =
  AuthenticatedStaffAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAdminRoute = AuthenticatedStaffAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-reservations': typeof MyReservationsRoute
  '/no-access': typeof NoAccessRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRoute
  '/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/staff/map': typeof AuthenticatedStaffMapRoute
  '/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-reservations': typeof MyReservationsRoute
  '/no-access': typeof NoAccessRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRoute
  '/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/staff/map': typeof AuthenticatedStaffMapRoute
  '/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/my-reservations': typeof MyReservationsRoute
  '/no-access': typeof NoAccessRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/_authenticated/staff/admin': typeof AuthenticatedStaffAdminRoute
  '/_authenticated/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/_authenticated/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/_authenticated/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/_authenticated/staff/map': typeof AuthenticatedStaffMapRoute
  '/_authenticated/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/_authenticated/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/_authenticated/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/_authenticated/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/_authenticated/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-reservations'
    | '/no-access'
    | '/signup'
    | '/venues'
    | '/staff'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/staff/admin'
    | '/staff/attendees'
    | '/staff/community-events'
    | '/staff/community-music'
    | '/staff/map'
    | '/staff/room-reservations'
    | '/staff/settings'
    | '/staff/sponsors'
    | '/staff/vendors'
    | '/staff/venues'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-reservations'
    | '/no-access'
    | '/signup'
    | '/venues'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/staff/admin'
    | '/staff/attendees'
    | '/staff/community-events'
    | '/staff/community-music'
    | '/staff/map'
    | '/staff/room-reservations'
    | '/staff/settings'
    | '/staff/sponsors'
    | '/staff/vendors'
    | '/staff/venues'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/my-reservations'
    | '/no-access'
    | '/signup'
    | '/venues'
    | '/_authenticated/staff'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/_authenticated/staff/admin'
    | '/_authenticated/staff/attendees'
    | '/_authenticated/staff/community-events'
    | '/_authenticated/staff/community-music'
    | '/_authenticated/staff/map'
    | '/_authenticated/staff/room-reservations'
    | '/_authenticated/staff/settings'
    | '/_authenticated/staff/sponsors'
    | '/_authenticated/staff/vendors'
    | '/_authenticated/staff/venues'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyReservationsRoute: typeof MyReservationsRoute
  NoAccessRoute: typeof NoAccessRoute
  SignupRoute: typeof SignupRoute
  VenuesRoute: typeof VenuesRouteWithChildren
  RoomsIdRoute: typeof RoomsIdRoute
  StagesIdRoute: typeof StagesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$id': {
      id: '/venues/$id'
      path: '/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof VenuesIdRouteImport
      parentRoute: typeof VenuesRoute
    }
    '/stages/$id': {
      id: '/stages/$id'
      path: '/stages/$id'
      fullPath: '/stages/$id'
      preLoaderRoute: typeof StagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/venues': {
      id: '/_authenticated/staff/venues'
      path: '/venues'
      fullPath: '/staff/venues'
      preLoaderRoute: typeof AuthenticatedStaffVenuesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/vendors': {
      id: '/_authenticated/staff/vendors'
      path: '/vendors'
      fullPath: '/staff/vendors'
      preLoaderRoute: typeof AuthenticatedStaffVendorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/sponsors': {
      id: '/_authenticated/staff/sponsors'
      path: '/sponsors'
      fullPath: '/staff/sponsors'
      preLoaderRoute: typeof AuthenticatedStaffSponsorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/settings': {
      id: '/_authenticated/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof AuthenticatedStaffSettingsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/room-reservations': {
      id: '/_authenticated/staff/room-reservations'
      path: '/room-reservations'
      fullPath: '/staff/room-reservations'
      preLoaderRoute: typeof AuthenticatedStaffRoomReservationsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/map': {
      id: '/_authenticated/staff/map'
      path: '/map'
      fullPath: '/staff/map'
      preLoaderRoute: typeof AuthenticatedStaffMapRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/community-music': {
      id: '/_authenticated/staff/community-music'
      path: '/community-music'
      fullPath: '/staff/community-music'
      preLoaderRoute: typeof AuthenticatedStaffCommunityMusicRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/community-events': {
      id: '/_authenticated/staff/community-events'
      path: '/community-events'
      fullPath: '/staff/community-events'
      preLoaderRoute: typeof AuthenticatedStaffCommunityEventsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/attendees': {
      id: '/_authenticated/staff/attendees'
      path: '/attendees'
      fullPath: '/staff/attendees'
      preLoaderRoute: typeof AuthenticatedStaffAttendeesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/admin': {
      id: '/_authenticated/staff/admin'
      path: '/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof AuthenticatedStaffAdminRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
  }
}

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAdminRoute: typeof AuthenticatedStaffAdminRoute
  AuthenticatedStaffAttendeesRoute: typeof AuthenticatedStaffAttendeesRoute
  AuthenticatedStaffCommunityEventsRoute: typeof AuthenticatedStaffCommunityEventsRoute
  AuthenticatedStaffCommunityMusicRoute: typeof AuthenticatedStaffCommunityMusicRoute
  AuthenticatedStaffMapRoute: typeof AuthenticatedStaffMapRoute
  AuthenticatedStaffRoomReservationsRoute: typeof AuthenticatedStaffRoomReservationsRoute
  AuthenticatedStaffSettingsRoute: typeof AuthenticatedStaffSettingsRoute
  AuthenticatedStaffSponsorsRoute: typeof AuthenticatedStaffSponsorsRoute
  AuthenticatedStaffVendorsRoute: typeof AuthenticatedStaffVendorsRoute
  AuthenticatedStaffVenuesRoute: typeof AuthenticatedStaffVenuesRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAdminRoute: AuthenticatedStaffAdminRoute,
  AuthenticatedStaffAttendeesRoute: AuthenticatedStaffAttendeesRoute,
  AuthenticatedStaffCommunityEventsRoute:
    AuthenticatedStaffCommunityEventsRoute,
  AuthenticatedStaffCommunityMusicRoute: AuthenticatedStaffCommunityMusicRoute,
  AuthenticatedStaffMapRoute: AuthenticatedStaffMapRoute,
  AuthenticatedStaffRoomReservationsRoute:
    AuthenticatedStaffRoomReservationsRoute,
  AuthenticatedStaffSettingsRoute: AuthenticatedStaffSettingsRoute,
  AuthenticatedStaffSponsorsRoute: AuthenticatedStaffSponsorsRoute,
  AuthenticatedStaffVendorsRoute: AuthenticatedStaffVendorsRoute,
  AuthenticatedStaffVenuesRoute: AuthenticatedStaffVenuesRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VenuesRouteChildren {
  VenuesIdRoute: typeof VenuesIdRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesIdRoute: VenuesIdRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MyReservationsRoute: MyReservationsRoute,
  NoAccessRoute: NoAccessRoute,
  SignupRoute: SignupRoute,
  VenuesRoute: VenuesRouteWithChildren,
  RoomsIdRoute: RoomsIdRoute,
  StagesIdRoute: StagesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
