/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as StreetbeatsRouteImport } from './routes/streetbeats'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as VenuesIdRouteImport } from './routes/venues.$id'
import { Route as StagesIdRouteImport } from './routes/stages.$id'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as CommunityEventsIdRouteImport } from './routes/community-events.$id'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedMyTicketsRouteImport } from './routes/_authenticated/my-tickets'
import { Route as AuthenticatedMyScheduleRouteImport } from './routes/_authenticated/my-schedule'
import { Route as AuthenticatedMyReservationsRouteImport } from './routes/_authenticated/my-reservations'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStreetbeatsMyGigsRouteImport } from './routes/_authenticated/streetbeats/my-gigs'
import { Route as AuthenticatedStreetbeatsApplyRouteImport } from './routes/_authenticated/streetbeats/apply'
import { Route as AuthenticatedStaffVenuesRouteImport } from './routes/_authenticated/staff/venues'
import { Route as AuthenticatedStaffVendorsRouteImport } from './routes/_authenticated/staff/vendors'
import { Route as AuthenticatedStaffSponsorsRouteImport } from './routes/_authenticated/staff/sponsors'
import { Route as AuthenticatedStaffSettingsRouteImport } from './routes/_authenticated/staff/settings'
import { Route as AuthenticatedStaffRoomReservationsRouteImport } from './routes/_authenticated/staff/room-reservations'
import { Route as AuthenticatedStaffMapRouteImport } from './routes/_authenticated/staff/map'
import { Route as AuthenticatedStaffCommunityOrganizationsRouteImport } from './routes/_authenticated/staff/community-organizations'
import { Route as AuthenticatedStaffCommunityMusicRouteImport } from './routes/_authenticated/staff/community-music'
import { Route as AuthenticatedStaffCommunityEventsRouteImport } from './routes/_authenticated/staff/community-events'
import { Route as AuthenticatedStaffClassesRouteImport } from './routes/_authenticated/staff/classes'
import { Route as AuthenticatedStaffAttendeesRouteImport } from './routes/_authenticated/staff/attendees'
import { Route as AuthenticatedStaffAdminRouteImport } from './routes/_authenticated/staff/admin'
import { Route as AuthenticatedCommunityManageRouteImport } from './routes/_authenticated/community/manage'
import { Route as AuthenticatedCommunityApplyRouteImport } from './routes/_authenticated/community/apply'
import { Route as AuthenticatedStaffEventsIdRouteImport } from './routes/_authenticated/staff/events.$id'
import { Route as AuthenticatedStaffAdminSocialIntegrationsRouteImport } from './routes/_authenticated/staff/admin.social-integrations'
import { Route as AuthenticatedStaffAdminSocialRouteImport } from './routes/_authenticated/staff/admin.social'
import { Route as AuthenticatedStaffAdminPermissionsRouteImport } from './routes/_authenticated/staff/admin.permissions'
import { Route as AuthenticatedStaffAdminGuidebookPublisherRouteImport } from './routes/_authenticated/staff/admin.guidebook-publisher'
import { Route as AuthenticatedStaffAdminGuidebookCanvasRouteImport } from './routes/_authenticated/staff/admin.guidebook-canvas'
import { Route as AuthenticatedStaffAdminGuidebookRouteImport } from './routes/_authenticated/staff/admin.guidebook'
import { Route as AuthenticatedStaffAdminDepartmentsRouteImport } from './routes/_authenticated/staff/admin.departments'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth/meta/callback'
import { Route as ApiPublicOauthLinkedinCallbackRouteImport } from './routes/api/public/oauth/linkedin/callback'
import { Route as AuthenticatedStaffAdminSocialConnectionsRouteImport } from './routes/_authenticated/staff/admin.social.connections'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetbeatsRoute = StreetbeatsRouteImport.update({
  id: '/streetbeats',
  path: '/streetbeats',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIdRoute = VenuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VenuesRoute,
} as any)
const StagesIdRoute = StagesIdRouteImport.update({
  id: '/stages/$id',
  path: '/stages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/gigs/$id',
  path: '/gigs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIdRoute = CommunityEventsIdRouteImport.update({
  id: '/community-events/$id',
  path: '/community-events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassesRoute,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyTicketsRoute = AuthenticatedMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyScheduleRoute = AuthenticatedMyScheduleRouteImport.update({
  id: '/my-schedule',
  path: '/my-schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyReservationsRoute =
  AuthenticatedMyReservationsRouteImport.update({
    id: '/my-reservations',
    path: '/my-reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStreetbeatsMyGigsRoute =
  AuthenticatedStreetbeatsMyGigsRouteImport.update({
    id: '/streetbeats/my-gigs',
    path: '/streetbeats/my-gigs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStreetbeatsApplyRoute =
  AuthenticatedStreetbeatsApplyRouteImport.update({
    id: '/streetbeats/apply',
    path: '/streetbeats/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffVenuesRoute =
  AuthenticatedStaffVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffVendorsRoute =
  AuthenticatedStaffVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSponsorsRoute =
  AuthenticatedStaffSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSettingsRoute =
  AuthenticatedStaffSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffRoomReservationsRoute =
  AuthenticatedStaffRoomReservationsRouteImport.update({
    id: '/room-reservations',
    path: '/room-reservations',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffMapRoute = AuthenticatedStaffMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffCommunityOrganizationsRoute =
  AuthenticatedStaffCommunityOrganizationsRouteImport.update({
    id: '/community-organizations',
    path: '/community-organizations',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCommunityMusicRoute =
  AuthenticatedStaffCommunityMusicRouteImport.update({
    id: '/community-music',
    path: '/community-music',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCommunityEventsRoute =
  AuthenticatedStaffCommunityEventsRouteImport.update({
    id: '/community-events',
    path: '/community-events',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffClassesRoute =
  AuthenticatedStaffClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAttendeesRoute =
  AuthenticatedStaffAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAdminRoute = AuthenticatedStaffAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedCommunityManageRoute =
  AuthenticatedCommunityManageRouteImport.update({
    id: '/community/manage',
    path: '/community/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityApplyRoute =
  AuthenticatedCommunityApplyRouteImport.update({
    id: '/community/apply',
    path: '/community/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffEventsIdRoute =
  AuthenticatedStaffEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAdminSocialIntegrationsRoute =
  AuthenticatedStaffAdminSocialIntegrationsRouteImport.update({
    id: '/social-integrations',
    path: '/social-integrations',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminSocialRoute =
  AuthenticatedStaffAdminSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminPermissionsRoute =
  AuthenticatedStaffAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminGuidebookPublisherRoute =
  AuthenticatedStaffAdminGuidebookPublisherRouteImport.update({
    id: '/guidebook-publisher',
    path: '/guidebook-publisher',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminGuidebookCanvasRoute =
  AuthenticatedStaffAdminGuidebookCanvasRouteImport.update({
    id: '/guidebook-canvas',
    path: '/guidebook-canvas',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminGuidebookRoute =
  AuthenticatedStaffAdminGuidebookRouteImport.update({
    id: '/guidebook',
    path: '/guidebook',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const AuthenticatedStaffAdminDepartmentsRoute =
  AuthenticatedStaffAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedStaffAdminRoute,
  } as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthLinkedinCallbackRoute =
  ApiPublicOauthLinkedinCallbackRouteImport.update({
    id: '/api/public/oauth/linkedin/callback',
    path: '/api/public/oauth/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStaffAdminSocialConnectionsRoute =
  AuthenticatedStaffAdminSocialConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedStaffAdminSocialRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRouteWithChildren
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/streetbeats': typeof StreetbeatsRoute
  '/vendor': typeof VendorRoute
  '/venues': typeof VenuesRouteWithChildren
  '/hub': typeof AuthenticatedHubRoute
  '/my-reservations': typeof AuthenticatedMyReservationsRoute
  '/my-schedule': typeof AuthenticatedMyScheduleRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/artists/$id': typeof ArtistsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/events/': typeof EventsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/community/apply': typeof AuthenticatedCommunityApplyRoute
  '/community/manage': typeof AuthenticatedCommunityManageRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRouteWithChildren
  '/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/staff/classes': typeof AuthenticatedStaffClassesRoute
  '/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/staff/community-organizations': typeof AuthenticatedStaffCommunityOrganizationsRoute
  '/staff/map': typeof AuthenticatedStaffMapRoute
  '/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/streetbeats/apply': typeof AuthenticatedStreetbeatsApplyRoute
  '/streetbeats/my-gigs': typeof AuthenticatedStreetbeatsMyGigsRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/staff/admin/departments': typeof AuthenticatedStaffAdminDepartmentsRoute
  '/staff/admin/guidebook': typeof AuthenticatedStaffAdminGuidebookRoute
  '/staff/admin/guidebook-canvas': typeof AuthenticatedStaffAdminGuidebookCanvasRoute
  '/staff/admin/guidebook-publisher': typeof AuthenticatedStaffAdminGuidebookPublisherRoute
  '/staff/admin/permissions': typeof AuthenticatedStaffAdminPermissionsRoute
  '/staff/admin/social': typeof AuthenticatedStaffAdminSocialRouteWithChildren
  '/staff/admin/social-integrations': typeof AuthenticatedStaffAdminSocialIntegrationsRoute
  '/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/staff/admin/social/connections': typeof AuthenticatedStaffAdminSocialConnectionsRoute
  '/api/public/oauth/linkedin/callback': typeof ApiPublicOauthLinkedinCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRouteWithChildren
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/streetbeats': typeof StreetbeatsRoute
  '/vendor': typeof VendorRoute
  '/venues': typeof VenuesRouteWithChildren
  '/hub': typeof AuthenticatedHubRoute
  '/my-reservations': typeof AuthenticatedMyReservationsRoute
  '/my-schedule': typeof AuthenticatedMyScheduleRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/events': typeof EventsIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/community/apply': typeof AuthenticatedCommunityApplyRoute
  '/community/manage': typeof AuthenticatedCommunityManageRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRouteWithChildren
  '/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/staff/classes': typeof AuthenticatedStaffClassesRoute
  '/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/staff/community-organizations': typeof AuthenticatedStaffCommunityOrganizationsRoute
  '/staff/map': typeof AuthenticatedStaffMapRoute
  '/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/streetbeats/apply': typeof AuthenticatedStreetbeatsApplyRoute
  '/streetbeats/my-gigs': typeof AuthenticatedStreetbeatsMyGigsRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/staff/admin/departments': typeof AuthenticatedStaffAdminDepartmentsRoute
  '/staff/admin/guidebook': typeof AuthenticatedStaffAdminGuidebookRoute
  '/staff/admin/guidebook-canvas': typeof AuthenticatedStaffAdminGuidebookCanvasRoute
  '/staff/admin/guidebook-publisher': typeof AuthenticatedStaffAdminGuidebookPublisherRoute
  '/staff/admin/permissions': typeof AuthenticatedStaffAdminPermissionsRoute
  '/staff/admin/social': typeof AuthenticatedStaffAdminSocialRouteWithChildren
  '/staff/admin/social-integrations': typeof AuthenticatedStaffAdminSocialIntegrationsRoute
  '/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/staff/admin/social/connections': typeof AuthenticatedStaffAdminSocialConnectionsRoute
  '/api/public/oauth/linkedin/callback': typeof ApiPublicOauthLinkedinCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/classes': typeof ClassesRouteWithChildren
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/streetbeats': typeof StreetbeatsRoute
  '/vendor': typeof VendorRoute
  '/venues': typeof VenuesRouteWithChildren
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/my-reservations': typeof AuthenticatedMyReservationsRoute
  '/_authenticated/my-schedule': typeof AuthenticatedMyScheduleRoute
  '/_authenticated/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/artists/$id': typeof ArtistsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/stages/$id': typeof StagesIdRoute
  '/venues/$id': typeof VenuesIdRoute
  '/events/': typeof EventsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/_authenticated/community/apply': typeof AuthenticatedCommunityApplyRoute
  '/_authenticated/community/manage': typeof AuthenticatedCommunityManageRoute
  '/_authenticated/staff/admin': typeof AuthenticatedStaffAdminRouteWithChildren
  '/_authenticated/staff/attendees': typeof AuthenticatedStaffAttendeesRoute
  '/_authenticated/staff/classes': typeof AuthenticatedStaffClassesRoute
  '/_authenticated/staff/community-events': typeof AuthenticatedStaffCommunityEventsRoute
  '/_authenticated/staff/community-music': typeof AuthenticatedStaffCommunityMusicRoute
  '/_authenticated/staff/community-organizations': typeof AuthenticatedStaffCommunityOrganizationsRoute
  '/_authenticated/staff/map': typeof AuthenticatedStaffMapRoute
  '/_authenticated/staff/room-reservations': typeof AuthenticatedStaffRoomReservationsRoute
  '/_authenticated/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/_authenticated/staff/sponsors': typeof AuthenticatedStaffSponsorsRoute
  '/_authenticated/staff/vendors': typeof AuthenticatedStaffVendorsRoute
  '/_authenticated/staff/venues': typeof AuthenticatedStaffVenuesRoute
  '/_authenticated/streetbeats/apply': typeof AuthenticatedStreetbeatsApplyRoute
  '/_authenticated/streetbeats/my-gigs': typeof AuthenticatedStreetbeatsMyGigsRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/staff/admin/departments': typeof AuthenticatedStaffAdminDepartmentsRoute
  '/_authenticated/staff/admin/guidebook': typeof AuthenticatedStaffAdminGuidebookRoute
  '/_authenticated/staff/admin/guidebook-canvas': typeof AuthenticatedStaffAdminGuidebookCanvasRoute
  '/_authenticated/staff/admin/guidebook-publisher': typeof AuthenticatedStaffAdminGuidebookPublisherRoute
  '/_authenticated/staff/admin/permissions': typeof AuthenticatedStaffAdminPermissionsRoute
  '/_authenticated/staff/admin/social': typeof AuthenticatedStaffAdminSocialRouteWithChildren
  '/_authenticated/staff/admin/social-integrations': typeof AuthenticatedStaffAdminSocialIntegrationsRoute
  '/_authenticated/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/_authenticated/staff/admin/social/connections': typeof AuthenticatedStaffAdminSocialConnectionsRoute
  '/api/public/oauth/linkedin/callback': typeof ApiPublicOauthLinkedinCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/community'
    | '/forgot-password'
    | '/login'
    | '/manual'
    | '/no-access'
    | '/reset-password'
    | '/signup'
    | '/sponsors'
    | '/streetbeats'
    | '/vendor'
    | '/venues'
    | '/hub'
    | '/my-reservations'
    | '/my-schedule'
    | '/my-tickets'
    | '/staff'
    | '/artists/$id'
    | '/classes/$id'
    | '/community-events/$id'
    | '/departments/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/events/'
    | '/rooms/'
    | '/community/apply'
    | '/community/manage'
    | '/staff/admin'
    | '/staff/attendees'
    | '/staff/classes'
    | '/staff/community-events'
    | '/staff/community-music'
    | '/staff/community-organizations'
    | '/staff/map'
    | '/staff/room-reservations'
    | '/staff/settings'
    | '/staff/sponsors'
    | '/staff/vendors'
    | '/staff/venues'
    | '/streetbeats/apply'
    | '/streetbeats/my-gigs'
    | '/staff/'
    | '/staff/admin/departments'
    | '/staff/admin/guidebook'
    | '/staff/admin/guidebook-canvas'
    | '/staff/admin/guidebook-publisher'
    | '/staff/admin/permissions'
    | '/staff/admin/social'
    | '/staff/admin/social-integrations'
    | '/staff/events/$id'
    | '/staff/admin/social/connections'
    | '/api/public/oauth/linkedin/callback'
    | '/api/public/oauth/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/community'
    | '/forgot-password'
    | '/login'
    | '/manual'
    | '/no-access'
    | '/reset-password'
    | '/signup'
    | '/sponsors'
    | '/streetbeats'
    | '/vendor'
    | '/venues'
    | '/hub'
    | '/my-reservations'
    | '/my-schedule'
    | '/my-tickets'
    | '/artists/$id'
    | '/classes/$id'
    | '/community-events/$id'
    | '/departments/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/events'
    | '/rooms'
    | '/community/apply'
    | '/community/manage'
    | '/staff/admin'
    | '/staff/attendees'
    | '/staff/classes'
    | '/staff/community-events'
    | '/staff/community-music'
    | '/staff/community-organizations'
    | '/staff/map'
    | '/staff/room-reservations'
    | '/staff/settings'
    | '/staff/sponsors'
    | '/staff/vendors'
    | '/staff/venues'
    | '/streetbeats/apply'
    | '/streetbeats/my-gigs'
    | '/staff'
    | '/staff/admin/departments'
    | '/staff/admin/guidebook'
    | '/staff/admin/guidebook-canvas'
    | '/staff/admin/guidebook-publisher'
    | '/staff/admin/permissions'
    | '/staff/admin/social'
    | '/staff/admin/social-integrations'
    | '/staff/events/$id'
    | '/staff/admin/social/connections'
    | '/api/public/oauth/linkedin/callback'
    | '/api/public/oauth/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/classes'
    | '/community'
    | '/forgot-password'
    | '/login'
    | '/manual'
    | '/no-access'
    | '/reset-password'
    | '/signup'
    | '/sponsors'
    | '/streetbeats'
    | '/vendor'
    | '/venues'
    | '/_authenticated/hub'
    | '/_authenticated/my-reservations'
    | '/_authenticated/my-schedule'
    | '/_authenticated/my-tickets'
    | '/_authenticated/staff'
    | '/artists/$id'
    | '/classes/$id'
    | '/community-events/$id'
    | '/departments/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/rooms/$id'
    | '/stages/$id'
    | '/venues/$id'
    | '/events/'
    | '/rooms/'
    | '/_authenticated/community/apply'
    | '/_authenticated/community/manage'
    | '/_authenticated/staff/admin'
    | '/_authenticated/staff/attendees'
    | '/_authenticated/staff/classes'
    | '/_authenticated/staff/community-events'
    | '/_authenticated/staff/community-music'
    | '/_authenticated/staff/community-organizations'
    | '/_authenticated/staff/map'
    | '/_authenticated/staff/room-reservations'
    | '/_authenticated/staff/settings'
    | '/_authenticated/staff/sponsors'
    | '/_authenticated/staff/vendors'
    | '/_authenticated/staff/venues'
    | '/_authenticated/streetbeats/apply'
    | '/_authenticated/streetbeats/my-gigs'
    | '/_authenticated/staff/'
    | '/_authenticated/staff/admin/departments'
    | '/_authenticated/staff/admin/guidebook'
    | '/_authenticated/staff/admin/guidebook-canvas'
    | '/_authenticated/staff/admin/guidebook-publisher'
    | '/_authenticated/staff/admin/permissions'
    | '/_authenticated/staff/admin/social'
    | '/_authenticated/staff/admin/social-integrations'
    | '/_authenticated/staff/events/$id'
    | '/_authenticated/staff/admin/social/connections'
    | '/api/public/oauth/linkedin/callback'
    | '/api/public/oauth/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ClassesRoute: typeof ClassesRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  NoAccessRoute: typeof NoAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SponsorsRoute: typeof SponsorsRoute
  StreetbeatsRoute: typeof StreetbeatsRoute
  VendorRoute: typeof VendorRoute
  VenuesRoute: typeof VenuesRouteWithChildren
  ArtistsIdRoute: typeof ArtistsIdRoute
  CommunityEventsIdRoute: typeof CommunityEventsIdRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  EventsIdRoute: typeof EventsIdRoute
  GigsIdRoute: typeof GigsIdRoute
  RoomsIdRoute: typeof RoomsIdRoute
  StagesIdRoute: typeof StagesIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  ApiPublicOauthLinkedinCallbackRoute: typeof ApiPublicOauthLinkedinCallbackRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streetbeats': {
      id: '/streetbeats'
      path: '/streetbeats'
      fullPath: '/streetbeats'
      preLoaderRoute: typeof StreetbeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$id': {
      id: '/venues/$id'
      path: '/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof VenuesIdRouteImport
      parentRoute: typeof VenuesRoute
    }
    '/stages/$id': {
      id: '/stages/$id'
      path: '/stages/$id'
      fullPath: '/stages/$id'
      preLoaderRoute: typeof StagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/gigs/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/$id': {
      id: '/community-events/$id'
      path: '/community-events/$id'
      fullPath: '/community-events/$id'
      preLoaderRoute: typeof CommunityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$id': {
      id: '/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-tickets': {
      id: '/_authenticated/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedMyTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-schedule': {
      id: '/_authenticated/my-schedule'
      path: '/my-schedule'
      fullPath: '/my-schedule'
      preLoaderRoute: typeof AuthenticatedMyScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-reservations': {
      id: '/_authenticated/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof AuthenticatedMyReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/streetbeats/my-gigs': {
      id: '/_authenticated/streetbeats/my-gigs'
      path: '/streetbeats/my-gigs'
      fullPath: '/streetbeats/my-gigs'
      preLoaderRoute: typeof AuthenticatedStreetbeatsMyGigsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/streetbeats/apply': {
      id: '/_authenticated/streetbeats/apply'
      path: '/streetbeats/apply'
      fullPath: '/streetbeats/apply'
      preLoaderRoute: typeof AuthenticatedStreetbeatsApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/venues': {
      id: '/_authenticated/staff/venues'
      path: '/venues'
      fullPath: '/staff/venues'
      preLoaderRoute: typeof AuthenticatedStaffVenuesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/vendors': {
      id: '/_authenticated/staff/vendors'
      path: '/vendors'
      fullPath: '/staff/vendors'
      preLoaderRoute: typeof AuthenticatedStaffVendorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/sponsors': {
      id: '/_authenticated/staff/sponsors'
      path: '/sponsors'
      fullPath: '/staff/sponsors'
      preLoaderRoute: typeof AuthenticatedStaffSponsorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/settings': {
      id: '/_authenticated/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof AuthenticatedStaffSettingsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/room-reservations': {
      id: '/_authenticated/staff/room-reservations'
      path: '/room-reservations'
      fullPath: '/staff/room-reservations'
      preLoaderRoute: typeof AuthenticatedStaffRoomReservationsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/map': {
      id: '/_authenticated/staff/map'
      path: '/map'
      fullPath: '/staff/map'
      preLoaderRoute: typeof AuthenticatedStaffMapRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/community-organizations': {
      id: '/_authenticated/staff/community-organizations'
      path: '/community-organizations'
      fullPath: '/staff/community-organizations'
      preLoaderRoute: typeof AuthenticatedStaffCommunityOrganizationsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/community-music': {
      id: '/_authenticated/staff/community-music'
      path: '/community-music'
      fullPath: '/staff/community-music'
      preLoaderRoute: typeof AuthenticatedStaffCommunityMusicRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/community-events': {
      id: '/_authenticated/staff/community-events'
      path: '/community-events'
      fullPath: '/staff/community-events'
      preLoaderRoute: typeof AuthenticatedStaffCommunityEventsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/classes': {
      id: '/_authenticated/staff/classes'
      path: '/classes'
      fullPath: '/staff/classes'
      preLoaderRoute: typeof AuthenticatedStaffClassesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/attendees': {
      id: '/_authenticated/staff/attendees'
      path: '/attendees'
      fullPath: '/staff/attendees'
      preLoaderRoute: typeof AuthenticatedStaffAttendeesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/admin': {
      id: '/_authenticated/staff/admin'
      path: '/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof AuthenticatedStaffAdminRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/community/manage': {
      id: '/_authenticated/community/manage'
      path: '/community/manage'
      fullPath: '/community/manage'
      preLoaderRoute: typeof AuthenticatedCommunityManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/apply': {
      id: '/_authenticated/community/apply'
      path: '/community/apply'
      fullPath: '/community/apply'
      preLoaderRoute: typeof AuthenticatedCommunityApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/events/$id': {
      id: '/_authenticated/staff/events/$id'
      path: '/events/$id'
      fullPath: '/staff/events/$id'
      preLoaderRoute: typeof AuthenticatedStaffEventsIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/admin/social-integrations': {
      id: '/_authenticated/staff/admin/social-integrations'
      path: '/social-integrations'
      fullPath: '/staff/admin/social-integrations'
      preLoaderRoute: typeof AuthenticatedStaffAdminSocialIntegrationsRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/social': {
      id: '/_authenticated/staff/admin/social'
      path: '/social'
      fullPath: '/staff/admin/social'
      preLoaderRoute: typeof AuthenticatedStaffAdminSocialRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/permissions': {
      id: '/_authenticated/staff/admin/permissions'
      path: '/permissions'
      fullPath: '/staff/admin/permissions'
      preLoaderRoute: typeof AuthenticatedStaffAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/guidebook-publisher': {
      id: '/_authenticated/staff/admin/guidebook-publisher'
      path: '/guidebook-publisher'
      fullPath: '/staff/admin/guidebook-publisher'
      preLoaderRoute: typeof AuthenticatedStaffAdminGuidebookPublisherRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/guidebook-canvas': {
      id: '/_authenticated/staff/admin/guidebook-canvas'
      path: '/guidebook-canvas'
      fullPath: '/staff/admin/guidebook-canvas'
      preLoaderRoute: typeof AuthenticatedStaffAdminGuidebookCanvasRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/guidebook': {
      id: '/_authenticated/staff/admin/guidebook'
      path: '/guidebook'
      fullPath: '/staff/admin/guidebook'
      preLoaderRoute: typeof AuthenticatedStaffAdminGuidebookRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/_authenticated/staff/admin/departments': {
      id: '/_authenticated/staff/admin/departments'
      path: '/departments'
      fullPath: '/staff/admin/departments'
      preLoaderRoute: typeof AuthenticatedStaffAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRoute
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/linkedin/callback': {
      id: '/api/public/oauth/linkedin/callback'
      path: '/api/public/oauth/linkedin/callback'
      fullPath: '/api/public/oauth/linkedin/callback'
      preLoaderRoute: typeof ApiPublicOauthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/admin/social/connections': {
      id: '/_authenticated/staff/admin/social/connections'
      path: '/connections'
      fullPath: '/staff/admin/social/connections'
      preLoaderRoute: typeof AuthenticatedStaffAdminSocialConnectionsRouteImport
      parentRoute: typeof AuthenticatedStaffAdminSocialRoute
    }
  }
}

interface AuthenticatedStaffAdminSocialRouteChildren {
  AuthenticatedStaffAdminSocialConnectionsRoute: typeof AuthenticatedStaffAdminSocialConnectionsRoute
}

const AuthenticatedStaffAdminSocialRouteChildren: AuthenticatedStaffAdminSocialRouteChildren =
  {
    AuthenticatedStaffAdminSocialConnectionsRoute:
      AuthenticatedStaffAdminSocialConnectionsRoute,
  }

const AuthenticatedStaffAdminSocialRouteWithChildren =
  AuthenticatedStaffAdminSocialRoute._addFileChildren(
    AuthenticatedStaffAdminSocialRouteChildren,
  )

interface AuthenticatedStaffAdminRouteChildren {
  AuthenticatedStaffAdminDepartmentsRoute: typeof AuthenticatedStaffAdminDepartmentsRoute
  AuthenticatedStaffAdminGuidebookRoute: typeof AuthenticatedStaffAdminGuidebookRoute
  AuthenticatedStaffAdminGuidebookCanvasRoute: typeof AuthenticatedStaffAdminGuidebookCanvasRoute
  AuthenticatedStaffAdminGuidebookPublisherRoute: typeof AuthenticatedStaffAdminGuidebookPublisherRoute
  AuthenticatedStaffAdminPermissionsRoute: typeof AuthenticatedStaffAdminPermissionsRoute
  AuthenticatedStaffAdminSocialRoute: typeof AuthenticatedStaffAdminSocialRouteWithChildren
  AuthenticatedStaffAdminSocialIntegrationsRoute: typeof AuthenticatedStaffAdminSocialIntegrationsRoute
}

const AuthenticatedStaffAdminRouteChildren: AuthenticatedStaffAdminRouteChildren =
  {
    AuthenticatedStaffAdminDepartmentsRoute:
      AuthenticatedStaffAdminDepartmentsRoute,
    AuthenticatedStaffAdminGuidebookRoute:
      AuthenticatedStaffAdminGuidebookRoute,
    AuthenticatedStaffAdminGuidebookCanvasRoute:
      AuthenticatedStaffAdminGuidebookCanvasRoute,
    AuthenticatedStaffAdminGuidebookPublisherRoute:
      AuthenticatedStaffAdminGuidebookPublisherRoute,
    AuthenticatedStaffAdminPermissionsRoute:
      AuthenticatedStaffAdminPermissionsRoute,
    AuthenticatedStaffAdminSocialRoute:
      AuthenticatedStaffAdminSocialRouteWithChildren,
    AuthenticatedStaffAdminSocialIntegrationsRoute:
      AuthenticatedStaffAdminSocialIntegrationsRoute,
  }

const AuthenticatedStaffAdminRouteWithChildren =
  AuthenticatedStaffAdminRoute._addFileChildren(
    AuthenticatedStaffAdminRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAdminRoute: typeof AuthenticatedStaffAdminRouteWithChildren
  AuthenticatedStaffAttendeesRoute: typeof AuthenticatedStaffAttendeesRoute
  AuthenticatedStaffClassesRoute: typeof AuthenticatedStaffClassesRoute
  AuthenticatedStaffCommunityEventsRoute: typeof AuthenticatedStaffCommunityEventsRoute
  AuthenticatedStaffCommunityMusicRoute: typeof AuthenticatedStaffCommunityMusicRoute
  AuthenticatedStaffCommunityOrganizationsRoute: typeof AuthenticatedStaffCommunityOrganizationsRoute
  AuthenticatedStaffMapRoute: typeof AuthenticatedStaffMapRoute
  AuthenticatedStaffRoomReservationsRoute: typeof AuthenticatedStaffRoomReservationsRoute
  AuthenticatedStaffSettingsRoute: typeof AuthenticatedStaffSettingsRoute
  AuthenticatedStaffSponsorsRoute: typeof AuthenticatedStaffSponsorsRoute
  AuthenticatedStaffVendorsRoute: typeof AuthenticatedStaffVendorsRoute
  AuthenticatedStaffVenuesRoute: typeof AuthenticatedStaffVenuesRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffEventsIdRoute: typeof AuthenticatedStaffEventsIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAdminRoute: AuthenticatedStaffAdminRouteWithChildren,
  AuthenticatedStaffAttendeesRoute: AuthenticatedStaffAttendeesRoute,
  AuthenticatedStaffClassesRoute: AuthenticatedStaffClassesRoute,
  AuthenticatedStaffCommunityEventsRoute:
    AuthenticatedStaffCommunityEventsRoute,
  AuthenticatedStaffCommunityMusicRoute: AuthenticatedStaffCommunityMusicRoute,
  AuthenticatedStaffCommunityOrganizationsRoute:
    AuthenticatedStaffCommunityOrganizationsRoute,
  AuthenticatedStaffMapRoute: AuthenticatedStaffMapRoute,
  AuthenticatedStaffRoomReservationsRoute:
    AuthenticatedStaffRoomReservationsRoute,
  AuthenticatedStaffSettingsRoute: AuthenticatedStaffSettingsRoute,
  AuthenticatedStaffSponsorsRoute: AuthenticatedStaffSponsorsRoute,
  AuthenticatedStaffVendorsRoute: AuthenticatedStaffVendorsRoute,
  AuthenticatedStaffVenuesRoute: AuthenticatedStaffVenuesRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStaffEventsIdRoute: AuthenticatedStaffEventsIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedMyReservationsRoute: typeof AuthenticatedMyReservationsRoute
  AuthenticatedMyScheduleRoute: typeof AuthenticatedMyScheduleRoute
  AuthenticatedMyTicketsRoute: typeof AuthenticatedMyTicketsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedCommunityApplyRoute: typeof AuthenticatedCommunityApplyRoute
  AuthenticatedCommunityManageRoute: typeof AuthenticatedCommunityManageRoute
  AuthenticatedStreetbeatsApplyRoute: typeof AuthenticatedStreetbeatsApplyRoute
  AuthenticatedStreetbeatsMyGigsRoute: typeof AuthenticatedStreetbeatsMyGigsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedMyReservationsRoute: AuthenticatedMyReservationsRoute,
  AuthenticatedMyScheduleRoute: AuthenticatedMyScheduleRoute,
  AuthenticatedMyTicketsRoute: AuthenticatedMyTicketsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedCommunityApplyRoute: AuthenticatedCommunityApplyRoute,
  AuthenticatedCommunityManageRoute: AuthenticatedCommunityManageRoute,
  AuthenticatedStreetbeatsApplyRoute: AuthenticatedStreetbeatsApplyRoute,
  AuthenticatedStreetbeatsMyGigsRoute: AuthenticatedStreetbeatsMyGigsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ClassesRouteChildren {
  ClassesIdRoute: typeof ClassesIdRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesIdRoute: ClassesIdRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface VenuesRouteChildren {
  VenuesIdRoute: typeof VenuesIdRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesIdRoute: VenuesIdRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ClassesRoute: ClassesRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  NoAccessRoute: NoAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SponsorsRoute: SponsorsRoute,
  StreetbeatsRoute: StreetbeatsRoute,
  VendorRoute: VendorRoute,
  VenuesRoute: VenuesRouteWithChildren,
  ArtistsIdRoute: ArtistsIdRoute,
  CommunityEventsIdRoute: CommunityEventsIdRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  EventsIdRoute: EventsIdRoute,
  GigsIdRoute: GigsIdRoute,
  RoomsIdRoute: RoomsIdRoute,
  StagesIdRoute: StagesIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  ApiPublicOauthLinkedinCallbackRoute: ApiPublicOauthLinkedinCallbackRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
